### ISSUE TITLE
In order to build properly "config4j" command line tool need to be extracted

### ISSUE THREAD

**Issue by uded** [config4star/config4j#4]
This tool, as for version 1.1, resides in the main source tree. But the source tree rely on that tool to compile. It is a vicious circle..

**Comment by ciaran-mchale** [comment]
On Sun, 2013-01-20 at 07:21 -0800, Łukasz Rżanek wrote:

> This tool, as for version 1.1, resides in the main source tree. But
> the source tree rely on that tool to compile. It is a vicious circle..

Your analysis is slightly incorrect. This issue is discussed in
Section 3.6 of the "Config4\* Maintenance Guide":

http://www.config4star.org/config4star-maintenance-guide/architectural-overview.html#htoc20

The build system just needs to be able to perform a multi-step
build. I was able to achieve this easily with "make" for the
C++ version and with "ant" for the Java version. In general,
Maven is a bit more cumbersome to work with, but I can't
imagine that doing a multi-step build process is impossible
with Maven.

Regards,
Ciaran.

**Comment by uded** [comment]
It is possible, but not fully effective. Packaging and stuff like that can be achieved in many ways, but in order to provide a simple tool set for Maven I do believe it would be easiest to just "split" the tools from the library. Besides of that the Maven plugin that can speak with Eclipse would be a nice addition as well. This can be achieved without splitting the source code, but I am a great fan of keeping things componentized...

In other words the tool should have a dependency to the library but it should not be a part of the library. 
It might make sense to provide an "uber" JAR that will consist of both, but it is a different scenario.

To be honest I am looking a the code at the code right now and I do not fully understand the reasoning for a multi-step build process like that. I can fully agree with the behaviour of `config2j` tool and I can easily move that behaviour to a Maven plugin. But how the `Config2JNoCheck` case is handled is quite disturbing and unusual for me. This scenario create a circular dependency on classes and build process, which should be - generally - avoided at all cost. Besides of that relying on a library to build a tool that then the library uses to build itself _is_, of course, possible. But if it is a good idea... it's another question.

Let me think about for a while and I will get back to that issue. I got plenty of different cases to look at in the meantime.

**Comment by uded** [comment]
Right now I have made my research into the subject and, basically, the class being used in the build process is creating a Java source file which... import the content of the CFG file into the StringBuilder object. It makes no sense at all. One can easily include the CFG file in the JAR and read the content of that file using `ClassLoader.getResourceAsStream()` method...

Therefore I believe it makes no practical sense to keep the tools and the library within the same source code tree. Breaking that apart would enable one to use more libraries and add flexibility to the tool-set accompanying the library. The library is something that should be kept light and flexible, while tool set is basically a wrench tool to be used with the library - it should, by may not be simple and small as if there is a good reason to introduce new features it might be done separately from the library. BUT the tool set should follow the library development.
